questions = [{"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "Which Apollo mission was the first one to land on the Moon?", "correct_answer": "Apollo 11",
              "incorrect_answers": ["Apollo 10", "Apollo 9", "Apollo 13"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "What does the letter &#039;S&#039; stand for in &#039;NASA&#039;?",
              "correct_answer": "Space", "incorrect_answers": ["Science", "Society", "Star"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "What name is given to all baby marsupials?", "correct_answer": "Joey",
              "incorrect_answers": ["Calf", "Pup", "Cub"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "Which is the longest bone in the human body? ", "correct_answer": "Femur",
              "incorrect_answers": ["Scapula", "Fibula", "Ulna"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "Which gas forms about 78% of the Earth&rsquo;s atmosphere?", "correct_answer": "Nitrogen",
              "incorrect_answers": ["Oxygen", "Argon", "Carbon Dioxide"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "What is the powerhouse of the cell?", "correct_answer": "Mitochondria",
              "incorrect_answers": ["Ribosome", "Redbull", "Nucleus"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "What is the standard SI unit for temperature?", "correct_answer": "Kelvin",
              "incorrect_answers": ["Fahrenheit", "Celsius", "Rankine"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "How many planets make up our Solar System?", "correct_answer": "8",
              "incorrect_answers": ["7", "9", "6"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "How many chromosomes are in your body cells?", "correct_answer": "23",
              "incorrect_answers": ["21", "22", "24"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "What is the standard atomic weight of a Plutonium nucleus?", "correct_answer": "244",
              "incorrect_answers": ["94", "481", "128"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "What does LASER stand for?",
              "correct_answer": "Light amplification by stimulated emission of radiation",
              "incorrect_answers": ["Lite analysing by stereo ecorazer", "Light amplifier by standby energy of radio",
                                    "Life antimatter by standing entry of range"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "What animal takes part in Schrodinger;s most famous thought experiment?",
              "correct_answer": "Cat", "incorrect_answers": ["Dog", "Bat", "Butterfly"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "What is the speed of light in a vacuum?", "correct_answer": "299,792,458 m/s",
              "incorrect_answers": ["50,461 m/s", "308,215,043 m/s", "751,665,014,151 m/s"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "What lies at the center of our galaxy?", "correct_answer": "A black hole",
              "incorrect_answers": ["A wormhole", "A supernova", "A quasar"]},
             {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
              "question": "Dry ice is the solid form of what substance?", "correct_answer": "Carbon dioxide",
              "incorrect_answers": ["Nitrogen", "Ammonia", "Oxygen"]}]
